from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import os
from datetime import datetime

PDF_DIR = "static/reports"
if not os.path.exists(PDF_DIR):
    os.makedirs(PDF_DIR)

def generate_legal_notice(scan_data: dict, inspector_id: str = "MAH-LM-2026"):
    """
    Generates a formal legal notice PDF for a non-compliant product.
    Returns the file path to the generated PDF.
    """
    filename = f"Notice_{scan_data.get('scan_id', 'unknown')}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    filepath = os.path.join(PDF_DIR, filename)
    
    doc = SimpleDocTemplate(filepath, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Center', alignment=1))
    styles.add(ParagraphStyle(name='Right', alignment=2))
    
    story = []
    
    # Header
    story.append(Paragraph("<b>GOVERNMENT OF INDIA</b>", styles['Center']))
    story.append(Paragraph("<b>DEPARTMENT OF LEGAL METROLOGY</b>", styles['Center']))
    story.append(Spacer(1, 12))
    story.append(Paragraph("<b>LEGAL NOTICE FOR NON-COMPLIANCE</b>", styles['Center']))
    story.append(Spacer(1, 24))
    
    # Metadata
    story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%d-%b-%Y %H:%M')}", styles['Normal']))
    story.append(Paragraph(f"<b>Notice ID:</b> LMN-{scan_data.get('scan_id', '1001')}", styles['Normal']))
    story.append(Paragraph(f"<b>Issuing Officer:</b> {inspector_id}", styles['Normal']))
    story.append(Spacer(1, 24))
    
    # Body
    body_text = f"""
    To Whom It May Concern,<br/><br/>
    This notice is issued under the <b>Legal Metrology (Packaged Commodities) Rules, 2011</b>. 
    During an official inspection, an AI-assisted scan of your packaged commodity revealed the following violations:
    """
    story.append(Paragraph(body_text, styles['Normal']))
    story.append(Spacer(1, 12))
    
    # Violations Data
    fraud_type = scan_data.get('fraud_type', 'Unspecified Violation')
    story.append(Paragraph(f"<font color='red'><b>Violation Detected:</b> {fraud_type}</font>", styles['Normal']))
    story.append(Spacer(1, 12))
    
    data = [
        ['Field', 'Detected Value', 'Status'],
        ['MRP', f"₹ {scan_data.get('scanned_mrp', 'N/A')}", 'Flagged' if 'MRP' in fraud_type else 'OK'],
        ['Mfg Date', scan_data.get('scanned_mfg_date', 'N/A'), 'Flagged' if 'Mfg' in fraud_type else 'OK'],
        ['Expiry Date', scan_data.get('scanned_exp_date', 'N/A'), 'Flagged' if 'Exp' in fraud_type else 'OK'],
        ['Net Weight', scan_data.get('scanned_net_weight', 'N/A'), 'Flagged' if 'Weight' in fraud_type else 'OK'],
    ]
    
    t = Table(data, colWidths=[120, 200, 100])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a365d')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
    ]))
    story.append(t)
    
    story.append(Spacer(1, 24))
    
    # Penalty
    story.append(Paragraph("<b>PENALTY CLAUSE:</b>", styles['Normal']))
    penalty_text = """
    As per Section 36 of the Legal Metrology Act, 2009, whoever manufactures, packs, imports, sells, 
    distributes, delivers or otherwise transfers, offers, exposes or possesses for sale, or causes to 
    be sold, distributed, delivered or otherwise transferred, offered, exposed for sale any pre-packaged 
    commodity which does not conform to the declarations on the package, shall be punished with fine 
    which may extend to twenty-five thousand rupees.
    """
    story.append(Paragraph(penalty_text, styles['Normal']))
    
    story.append(Spacer(1, 40))
    story.append(Paragraph("<i>Electronically Generated by VidhiScan AI Engine</i>", styles['Center']))
    
    doc.build(story)
    
    return f"/{filepath}"
